package main

import (
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

type PortAllocator struct {
	baseDir     string
	ports       map[string]int
	maxAttempts int
}

type ServicePorts struct {
	WEB          int
	API          int
	PG           int
	REDIS        int
	MINIO        int
	MINIO_CONSOLE int
}

func NewPortAllocator(baseDir string) *PortAllocator {
	return &PortAllocator{
		baseDir:     baseDir,
		ports:       make(map[string]int),
		maxAttempts: 100,
	}
}

func (pa *PortAllocator) AllocatePorts() error {
	basePorts := ServicePorts{
		WEB:          3000,
		API:          8080,
		PG:           5432,
		REDIS:        6379,
		MINIO:        9000,
		MINIO_CONSOLE: 9001,
	}

	// Allocate ports
	pa.ports["WEB"] = pa.findAvailablePort(basePorts.WEB)
	pa.ports["API"] = pa.findAvailablePort(basePorts.API)
	pa.ports["PG"] = pa.findAvailablePort(basePorts.PG)
	pa.ports["REDIS"] = pa.findAvailablePort(basePorts.REDIS)
	pa.ports["MINIO"] = pa.findAvailablePort(basePorts.MINIO)
	pa.ports["MINIO_CONSOLE"] = pa.findAvailablePort(basePorts.MINIO_CONSOLE)

	// Ensure no collisions
	if err := pa.validateNoCollisions(); err != nil {
		return fmt.Errorf("port collision detected: %w", err)
	}

	// Generate files atomically
	if err := pa.generateEnvFile(); err != nil {
		return fmt.Errorf("failed to generate .env.generated: %w", err)
	}

	if err := pa.generateComposeOverride(); err != nil {
		return fmt.Errorf("failed to generate docker-compose.override.yml: %w", err)
	}

	return nil
}

func (pa *PortAllocator) findAvailablePort(basePort int) int {
	for i := 0; i < pa.maxAttempts; i++ {
		port := basePort + i
		if pa.isPortAvailable(port) {
			return port
		}
	}
	// Fallback: return base port even if in use (Docker will handle it)
	return basePort
}

func (pa *PortAllocator) isPortAvailable(port int) bool {
	addr := fmt.Sprintf(":%d", port)
	ln, err := net.Listen("tcp", addr)
	if err != nil {
		return false
	}
	ln.Close()
	return true
}

func (pa *PortAllocator) validateNoCollisions() error {
	seen := make(map[int]string)
	for service, port := range pa.ports {
		if existing, exists := seen[port]; exists {
			return fmt.Errorf("port %d allocated to both %s and %s", port, existing, service)
		}
		seen[port] = service
	}
	return nil
}

func (pa *PortAllocator) generateEnvFile() error {
	deployDir := filepath.Join(pa.baseDir, "deploy")
	if err := os.MkdirAll(deployDir, 0755); err != nil {
		return err
	}

	envPath := filepath.Join(deployDir, ".env.generated")
	content := fmt.Sprintf(`# Generated by port-allocator - DO NOT EDIT MANUALLY
# This file is regenerated on each docker-up

WEB_PORT=%d
API_PORT=%d
POSTGRES_PORT=%d
REDIS_PORT=%d
MINIO_PORT=%d
MINIO_CONSOLE_PORT=%d
`, pa.ports["WEB"], pa.ports["API"], pa.ports["PG"], pa.ports["REDIS"], pa.ports["MINIO"], pa.ports["MINIO_CONSOLE"])

	return os.WriteFile(envPath, []byte(content), 0644)
}

func (pa *PortAllocator) generateComposeOverride() error {
	deployDir := filepath.Join(pa.baseDir, "deploy")
	overridePath := filepath.Join(deployDir, "docker-compose.override.yml")

	content := fmt.Sprintf(`# Generated by port-allocator - DO NOT EDIT MANUALLY
# This file is regenerated on each docker-up

version: '3.8'

services:
  web:
    ports:
      - "%d:3000"
  
  api:
    ports:
      - "%d:8080"
  
  postgres:
    ports:
      - "%d:5432"
  
  redis:
    ports:
      - "%d:6379"
  
  minio:
    ports:
      - "%d:9000"
      - "%d:9001"
`, pa.ports["WEB"], pa.ports["API"], pa.ports["PG"], pa.ports["REDIS"], pa.ports["MINIO"], pa.ports["MINIO_CONSOLE"])

	return os.WriteFile(overridePath, []byte(content), 0644)
}

func (pa *PortAllocator) PrintPorts() {
	fmt.Println("Allocated ports:")
	for service, port := range pa.ports {
		fmt.Printf("  %s: %d\n", service, port)
	}
}

